### PR TITLE
fix ERROR: Must specify a 'request' field in the payload that matches…

### PR DESCRIPTION
**Pull request by dutu**
… the URL path

fix error on POST request (REST v1)

### CODE REVIEW

**Comment by robertkowalski** [comment]
@dutu can you rebase please?

**Comment by robertkowalski** [comment]
@dutu 
i get 

```
Error: Nonce is too small.
    at Request.error1 [as _callback] (/Users/robert/bitfinex/bitfinex-api-node/rest.js:62:17)
    at Request.self.callback (/Users/robert/bitfinex/bitfinex-api-node/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/robert/bitfinex/bitfinex-api-node/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/robert/bitfinex/bitfinex-api-node/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by dutu** [comment]
Can you try new API keys. I doubt the changes here can lead to "Nonce is too small" error

**Comment by robertkowalski** [comment]
that solved it, thanks.

i'll merge when the build is green (pls rebase)

**Comment by dutu** [comment]
pls check

**Comment by robertkowalski** [comment]
merged as b90221a2002e2297c6dbbcd9f8dc42f3ca6f2489

**Comment by robertkowalski** [comment]
1.0.1 is published now.

**Pull request closed without merging**
