### PR TITLE
Fixing tests and adding yarn and eslint

### PR DESCRIPTION
**Pull request by mjesuele**
Hey hey, love Bitfinex -- thanks for making this available.

I pulled the code to check out while using it to write a lil arbitrage bot and I noticed that there was some divergent coding style, and some parts using ES5 and others using ES6+, so I added an ESLint configuration based on the existing code, then tweaked it a bit to be stricter. I fixed as many of the errors as I could without a lot of messing with logic -- almost all of it was done automatically by ESLint.

I hope that you like the configuration, but I'm totally open to changing anything you find disagreeable. I made the vast majority of the fixes as a separate last commit (6e9b9ea) so it would be very easy to revert or alter.

I was also having trouble getting the test suite to pass. When I tried to diagnose the problem, I noticed that the line numbers for the errors I was getting were strange. I eventually realized that this was due to istanbul running beneath mocha, so I added a "test-without-coverage" script to package.json, and then I was able to get the correct line numbers.

I tracked the problems in the tests down to invalid API credentials and disabled those tests for now. You can see them at https://github.com/bitfinexcom/bitfinex-api-node/compare/master...mjesuele:fixing-tests-and-adding-yarn-and-eslint?expand=1#diff-98368409550a57ad0b763b75dcf4f95eR325 and https://github.com/bitfinexcom/bitfinex-api-node/compare/master...mjesuele:fixing-tests-and-adding-yarn-and-eslint?expand=1#diff-8e02710f822064f6f3b24fb6a90b300fR130.

Oh, and I also used yarn, which added a lockfile.

Happy to discuss anything. Thanks again!

### CODE REVIEW

**Comment by robertkowalski** [comment]
wow thats super cool <3

**Comment by mjesuele** [comment]
Thanks, @robertkowalski! Just trying to do my part :)

**Comment by prdn** [comment]
Thank you very much @mjesuele 
This looks really good :+1: :+1:

**Comment by mjesuele** [comment]
Woohoo! Glad y'all dig. Thanks! 😊

**Pull request merged**
