### PR TITLE
Allow passing of options to Rest Lendbook Call

### PR DESCRIPTION
**Pull request by acterry**
Needed ability to pass options like limit_asks and limit_bids to the lendbook public api endpoint.

I used the same technique as the orderbook function and I added test a test to make sure that the function works with and without the options argument being passed in.

When running the tests, I noticed the following:
- the WS info message test was expecting version 1 instead of the returned version 1.1
- the symbol details test was expecting different values for ethusd/ethbtc initial_margin & minimum_margin

I updated the expected values, assuming that Bitfinex had changed the version number and eth margin values and that the tests were just out of date. Let me know if I assumed wrong.

Wasn't sure whether or not to commit or discard all of the changes to the source/images/coverage/ files that the npm test generated. Not really a fan of how to exposes paths from my filesystem, but I committed them anyway in case you use them as part of your review to judge whether or not tests had been run.

Let me know if I missed any PR requirements. Thanks.

### CODE REVIEW

**Comment by joshuarossi** [comment]
So far this looks good. Plan to merge it later tonight.

**Comment by prdn** [comment]
Thanks @acterry

**Comment by acterry** [comment]
@prdn and @joshuarossi ..... thanks for the fast review and merge. I'll definitely issue more PRs if I run across anything that I need.

**Comment by prdn** [comment]
@acterry thanks for your collaboration, we are really looking forward towards your help

**Pull request merged**
