### PR TITLE
Expose key in message data

### PR DESCRIPTION
**Pull request by androng**
This helps applications know what symbol and resolution this data is for.

### CODE REVIEW

**Comment by robertkowalski** [comment]
Thank you for your contribution!

Can you elaborate how that data is used?

**Comment by androng** [comment]
When candle data comes in, i use the "key" attribute to identify which resolution (1m, 5m, 1h)  and what symbol the candle data is. Otherwise, the application has no way to identify which channel number corresponds to which symbol and resolution.

**Comment by androng** [comment]
I can then use that resolution and symbol to execute a trade on the new candle data.

**Comment by robertkowalski** [comment]
ok, i will check that out today!

**Comment by robertkowalski** [comment]
That makes totally sense!

Thank you!

**Pull request merged**
